# Generated by Django 3.2.7 on 2021-09-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('admin', 'Creating form'), ('fill', 'Filling form'), ('result', 'Form results')], max_length=6)),
            ],
        ),
    ]
