# Generated by Django 3.2.7 on 2021-09-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomForms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='CustomForms.customform')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='CustomForms.section')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=40)),
                ('widget_type', models.CharField(choices=[], max_length=10)),
                ('input_type', models.CharField(choices=[], max_length=10)),
                ('input', models.CharField(max_length=300)),
                ('required', models.BooleanField()),
                ('visible', models.BooleanField()),
                ('validators', models.JSONField()),
                ('props_css', models.CharField(blank=True, max_length=300)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='CustomForms.subsection')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.JSONField()),
                ('actions', models.JSONField()),
                ('conditional_widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Variable widgets+', to='CustomForms.widget')),
                ('fixed_widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomForms.widget')),
            ],
        ),
    ]
