# Generated by Django 3.2.7 on 2021-09-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomForms', '0002_action_section_subsection_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='input',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='props_css',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='validators',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('textwidget', 'Text Widget'), ('textwidget', 'Text Widget'), ('textwidget', 'Text Widget'), ('textwidget', 'Text Widget'), ('textwidget', 'Text Widget')], max_length=10),
        ),
    ]
