# Generated by Django 3.2.7 on 2021-09-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomForms', '0003_auto_20210915_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='input_type',
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('text', 'Text Widget'), ('number', 'Number Widget'), ('email', 'Email Widget'), ('password', 'Password Widget'), ('checkbox', 'Checkbox Widget')], max_length=10),
        ),
    ]
